# Generated by Django 6.0.6 on 2026-06-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglog',
            name='summary_text',
            field=models.TextField(blank=True, help_text='The summary pasted by the student'),
        ),
    ]
