# Generated by Django 6.0.6 on 2026-06-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_readinglog_summary_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=100)),
                ('badge_icon', models.CharField(default='🏆', max_length=10)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='grants.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'badge_name')},
            },
        ),
    ]
