# Generated by Django 6.0.6 on 2026-06-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='deposit_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
