# Generated by Django 6.0.6 on 2026-06-29 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_studentprofile_deposit_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='grants.studentprofile'),
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level', models.IntegerField()),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_earned', to='grants.studentprofile')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_generated', to='grants.studentprofile')),
            ],
        ),
    ]
